const express = require('express');
const os = require('os');

const app = express();
const port = process.env.PORT || 3000;

app.get('/api/health', (_req, res) => {
  res.json({
    status: 'ok',
    service: 'backend',
    hostname: os.hostname()
  });
});

app.get('/api/hello', (req, res) => {
  const name = req.query.name || 'anonymous';

  res.json({
    message: `Hello ${name}, this response was generated by the backend.`,
    service: 'backend',
    hostname: os.hostname(),
    query: req.query,
    timestamp: new Date().toISOString()
  });
});

app.listen(port, () => {
  console.log(`Backend listening on port ${port}`);
});
